fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    prefix: /easyadmin
miniusine:
    resource: "@MuBundle/Resources/config/routing.yml"

