<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmabfew\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmabfew/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZmabfew.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZmabfew\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZmabfew\appDevDebugProjectContainer([
    'container.build_hash' => 'Zmabfew',
    'container.build_id' => '3461e609',
    'container.build_time' => 1578045252,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmabfew');
